spring:
  # datasource Setting
  datasource:
    url: jdbc:h2:tcp://localhost/~/commerce
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA Setting
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # where in ( ) ??

  # Log Setting
  output:
    ansi:
      enabled: always

# Logging Setting
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # query parameter ??